---
- name: Extract flux path and register var
  set_fact: flux_bin_path={{ item.path }}
  with_items:
    "{{ kubernetes_tools }}"
  when: '"flux" in item.name'

- name: Remove flux app
  file:
    path: "{{ flux_bin_path }}"
    state: absent
  when: uninstall_tools

- name: Check if flux binary exists.
  stat:
    path: "{{ flux_bin_path }}"
  register: flux_check

- name: Check flux version.
  command: "{{ flux_bin_path }} version"
  failed_when: false
  changed_when: false
  register: flux_existing_version

- name: Detect host architecture and set facts
  set_fact: k8s_arch="amd64" kubectl_arch="amd64"
  register: result
  when: ansible_facts.architecture == "x86_64"

- name: Download flux binary
  get_url:
    url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/{{ k8s_platform }}/{{ k8s_arch }}/kubectl"
    checksum: "{{ kubectl_checksum_binary }}"
    dest: /tmp
  when: >
    (not kubectl_check.stat.exists or kubectl_version not in kubectl_existing_version.stdout)
    and not uninstall_tools
  notify: copy kubectl binary