---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    kubectl_bin_path: /usr/local/bin/kubectl
    helm_bin_path: /usr/local/bin/helm
    flux_bin_path: /usr/local/bin/flux

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check Helm version.
      command: "{{ helm_bin_path }} version"
      changed_when: false
      register: helm_verify_version

    - name: Verify Helm's version is {{ helm_version }}.
      assert:
        that:
          - helm_version in helm_verify_version.stdout

    - name: Check kubectl version.
      command: "{{ kubectl_bin_path }} version --client"
      changed_when: false
      register: kubectl_verify_version

    - name: Verify Kubectl's version is {{ kubectl_version }}.
      assert:
        that:
          - kubectl_version in kubectl_verify_version.stdout

    - name: Check flux version.
      command: "{{ flux_bin_path }} --version"
      changed_when: false
      register: flux_verify_version

    - name: Verify flux's version is {{ flux_version }}.
      assert:
        that:
          - flux_version in flux_verify_version.stdout
